config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/profile', to: 'pages#profile'

  get '/map', to: 'pages#map'

  get '/components', to: 'pages#components'

  resources :plants do
    resources :bookings, only: [:new, :create, :destroy]
  end

  # resources :bookings, only: [:index, :show, :destroy, :update] do
  #   resources :reviews, only: [:create, :index, :show]
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :plant
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
  belongs_to :user
  validates :common_name, presence: true
  validates :scientific_name, presence: true
  validates :family, presence: true
  validates :price, presence: true
  validates :address, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_names_and_family,
    against: [ :common_name, :scientific_name, :family ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  #Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:destroy]

  def new
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new
    authorize(@booking)
  end

  def create
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.plant = @plant
    authorize(@booking)
    if @booking.save
      redirect_to profile_path
    else
      redirect_to plant_path(@plant)
    end
  end

  def destroy
    @booking.destroy
    redirect_to root_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:booking])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :components, :map]

  def home
    if params[:query].present?
      @plants = policy_scope(Plant).search_by_names_and_family(params[:query])
    else
      @plants = []
    end
  end

  def components
  end

  def profile
    @bookings = Booking.where(user_id: current_user.id)
    @plants = Plant.where(user_id: current_user.id)
  end

  def map
    @plants = Plant.all
    @markers = @plants.geocoded.map do |plant|
      {
        lat: plant.latitude,
        lng: plant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { plant: plant })
      }
    end
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @plants = policy_scope(Plant).order(created_at: :desc)
  end

  def show
    authorize(@plant)
  end

  def new
    @plant = Plant.new
    authorize(@plant)
  end

  def create
    @plant = Plant.create(plant_params)
    @plant.user = current_user
    authorize(@plant)
    if @plant.save
      redirect_to plant_path(@plant)
    else
      render 'new'
    end
  end

  def edit
    authorize(@plant)
  end

  def update
    authorize @plant
    @plant.update(plant_params)
    redirect_to plant_path(@plant)
  end

  def destroy
    authorize(@plant)
    @plant.destroy
    redirect_to root_path
  end

  private

  def set_plant
    @plant = Plant.find(params[:id])
    authorize(@plant)
  end

  def plant_params
    params.require(:plant).permit(:common_name, :scientific_name, :family, :price, :address, :photo, :latitude, :longitude)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="text-dark mb-4">Rent a Plant</h2>

      <%= simple_form_for [@plant, @booking] do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end"} %>
        <%= f.button :submit, class: 'button-yellow mt-3 w-100' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LouerDesPlantes</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>

 <% if user_signed_in? %>
 <%= render 'components/navbar_login' %>
 <% else %>
 <%= render 'components/navbar_logout' %>
 <% end %>


 <%= yield %>
</body>
</html>

app/views/pages/_info_window.html.erb
<div class="card-map">
  <%= link_to plant_path(plant), class: "text-decoration-none" do %>
  <h3><%= plant.common_name %></h3>

<% end %>

    <div class="img-map" style="background-image: url('<%= cl_image_path plant.photo.key %>')"></div>
</div>




<p><%= plant.address %></p>

app/views/pages/components.html.erb
<div class="navbar-logged-out">
 <%= image_tag('logo-simple.png', class: "logo") %>
 <div id="login">
   <a href="#" class="button-green">login</a>
 </div>

</div>
<div class="m-3">
  spacer
</div>

<div class="navbar-logged-in">
 <%= image_tag('logo-simple.png', class: "logo") %>
 <div id="navbar-end">
  <div id="button">
    <a href="#" class="button-green">add plant</a>
  </div>
  <%= image_tag('julia-avatar.png', class: "avatar") %>
</div>
</div>


<div id="banner-main" class="mt-5">
  <div id="content">
    <%= image_tag('logo-big.png', class: "mb-4") %>
    <p class="mb-4">Rent a plant or share your plants with other renters</p>
    <div class="search__container">

     <input class="search__input" type="text" placeholder="find a plant">
   </div>
 </div>

</div>

<div class="container mt-5">
  <h1 class="mb-3">Components</h1>

  <a href="#" class="button-yellow">yellow</a>
  <a href="#" class="button-green">green</a>
  <a href="#" class="button-blue">blue</a>
  <a href="#" class="button-pink">pink</a>

  <div class="mt-5 mb-5">
   <!-- partial:index.partial.html -->
   <div class="search__container">

     <input class="search__input" type="text" placeholder="find a plant">
   </div>
 </div>

 <div class="card-plant mb-3">
   <div class="img"></div>
   <div class="card-plant-footer">
     <div>
       <h3>Plant Name</h3>
       <p>Scientific Name</p>
     </div>
     <h4>$20</h4>
   </div>


 </div>

 <div class="card-plant mb-5">
   <div class="img"></div>
   <div class="card-plant-footer">
     <div class="spacer">
     </div>
   </div>

 </div>
</div>

<div id="footer">
  <p>Made at Le Wagon</p>
</div>

app/views/pages/home.html.erb
<main data-controller="search" data-target="search.main" class="green d-flex flex-column h-100 align-center justify-content-center">
  <div class="banner-main">
    <div id="content">
      <%= image_tag('logo-big.png', class: "mb-4") %>
      <p id="subtitle" class="mb-4">Rent a plant or share your plants with other renters</p>
    </div>
    <div class="d-flex justify-content-between align-center flex-column">
      <div class="search__input">
      <%= form_tag root_path,     class: "d-flex justify-content-between", method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      placeholder: "search for a plant"
      %>
      <%= button_tag({type: 'submit', class: "button-blue-search"}) do %>
      <i class="fas fa-search"></i>
      <% end %>
      <% end %>
    </div>
      <%= link_to map_path, class: "button-yellow mt-3 w-100" do %>
          find a plant near you <i class="fas fa-map-marked-alt pl-1"></i>
      <% end %>

    </div>

  </div>
</div>
</main>
<!-- , 'data-action' => 'click->search#append'  -->
<%= render "plants/index", plants: @plants %>
<%= render 'components/footer-pinned' %>

app/views/pages/map.html.erb
<div class="container mt-5 mb-4">
  <div class="box">
   <h1>Find plants near you</h1>
   <div id="map"
   style="width: 100%; height: 48vh;"
   data-markers="<%= @markers.to_json %>"
   data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>"></div>
 </div>

 <div class="d-flex">
   <%= link_to root_path, class: "button-yellow w-100 mt-4" do %>
          or search all plants <i class="fas fa-search pl-1"></i>
      <% end %>
 </div>




</div>



<%= render 'components/footer-pinned' %>

app/views/pages/profile.html.erb
  <div class="container mt-5">
  <div class="profile mb-5 d-flex flex-row justify-content-between align-items-center">
    <div>
      <h3>Hello <%= @current_user.first_name %>!</h3>
      <p>You have <strong><%= @plants.count %> plants</strong>  available to rent and you have already rented <strong><%= @bookings.count %> plants</strong>.</p>
    </div>
    <div class="avatar-large" style="background-image: url('<%= cl_image_path @current_user.photo.key %>')"></div>

  </div>
  <div class="booked">
    <h2>Plants booked</h2>
    <div class="mt-5 d-flex flex-row justify-content-between flex-wrap">
      <% @bookings.each do |booking| %>
      <div class="card-booking mb-3">
        <div class="img" style="background-image: url('<%= cl_image_path booking.plant.photo.key %>')"></div>
        <div class="card-content">
          <div>
            <h3><%= booking.plant.common_name %></h3>
            <p>Booked from <%= booking.start_date.to_formatted_s(:short) %> to <%= booking.end_date.to_formatted_s(:short) %></p>
          </div>
          <h4>$<%= booking.plant.price %></h4>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="my-plants my-5">
    <h2>My plants</h2>
    <div class="mt-5 d-flex flex-row justify-content-between flex-wrap">
      <% @plants.each do |plant| %>
      <div class="card-booking mb-3">
        <div class="img" style="background-image: url('<%= cl_image_path plant.photo.key %>')"></div>
        <div class="card-content">
          <div>
            <h3><%= plant.common_name %></h3>
            <p><%= plant.scientific_name %></p>
          </div>
          <h4>$<%= plant.price %></h4>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<%= render 'components/footer' %>

app/views/plants/_index.html.erb
<div class="beige-bg w-100 d-flex justify-content-center">
  <div class="w-90">
    <h1 class="mt-5 mb-4"> <%= @plants.any? ? "Plants" : "" %> </h1>
        <div class="mt-4 mb-5 d-flex flex-row justify-content-between flex-wrap">
          <% @plants.each do |plant| %>
            <%= link_to plant_path(plant), class: "text-decoration-none" do %>

              <div class="card-plant mb-5">
                <div class="img" style="background-image: url('<%= cl_image_path plant.photo.key %>')"></div>
                <div class="card-plant-footer">
                  <div>
                    <h3><%= plant.common_name %></h3>
                    <p><%= plant.scientific_name %></p>
                  </div>
                  <h4>$<%= plant.price %></h4>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
  </div>
</div>

app/views/plants/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="text-dark">Update Plant</h2>

      <%= simple_form_for @plant do |f| %>
        <% if policy(plant).edit? %>
          <%= link_to "Update", edit_plant_path(plant) %>
        <% end %>
        <%= f.input :photo, as: :file %>
        <%= f.input :common_name %>
        <%= f.input :scientific_name %>
        <%= f.input :family %>
        <%= f.input :address %>
        <%= f.input :price %>
      <% end %>
    </div>
  </div>
</div>

app/views/plants/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="text-dark mb-4">Create a new Plant</h2>

      <%= simple_form_for @plant do |f| %>
        <%= f.input :common_name %>
        <%= f.input :scientific_name %>
        <%= f.input :family %>
        <%= f.input :address %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'button-yellow mt-3 w-100' %>
      <% end %>
    </div>
  </div>
</div>
<%= render 'components/footer-pinned' %>

app/views/plants/show.html.erb
<div class="beige-bg w-100">
  <div class="container vh-70 d-flex align-items-center justify-content-around mt-5 px-5 flex-wrap">
   <div>
    <div class="card-plant mb-5">
      <div class="img" style="background-image: url('<%= cl_image_path @plant.photo.key %>')"></div>
      <div class="card-plant-footer">
        <div class="spacer"></div>
      </div>
    </div>
  </div>

  <div>

    <h3 class="plant-common-name text-capitalize"><%= @plant.common_name %></h3>
    <p class="plant-scientific-name text-capitalize"><%= @plant.scientific_name %></p>

    <%= link_to(new_plant_booking_path(@plant)) do %>
    <button class= "button-buy float-right"> <i class="fas fa-cart-plus"></i> $<%= @plant.price %> </button>
    <% end %>
  </div>
</div>

<%= render "components/footer-pinned" %>